site_name: "Learning AWS by doing"
copyright: "Mohit Kumar"
dev_addr: "127.0.0.1:8000"
docs_dir: docs
site_author: "Mohit Kumar" 
site_description: "Learn AWS - by doing. A complete hands-on learning of AWS services."
repo_url: "https://github.com/mohitkr05/aws-learning-by-doing"


theme:
    name: lumen


# extra_css:
#   - stylesheets/extra.css

nav:
  - Home: "index.md"
  - AI-CLF01: "aws-ai-practitioner-certification/docs/index.md"
  - Join Discord:  "https://discord.gg/tnZnWqnu9F"

markdown_extensions:
  - extra
  - toc
  - codehilite
  - tables
  - meta 
  - toc
  - footnotes
  - admonition
  - attr_list