site_name: "AWS Learning by doing"
copyright: "Mohit Kumar"
dev_addr: "127.0.0.1:8000"
docs_dir: docs
site_author: "Mohit Kumar" 
site_description: "AWS learning by doing"
repo_url: "https://github.com/mohitkr05/aws-learning-by-doing"


theme:
    name: journal


# extra_css:
#   - stylesheets/extra.css

nav:
  - Home: "index.md"
  - Join Discord:  "https://discord.gg/tnZnWqnu9F"

markdown_extensions:
  - extra
  - toc
  - codehilite
  - tables
  - meta 
  - toc
  - footnotes
  - admonition
  - attr_list