site_name: "101 Days of AWS"
copyright: "Mohit Kumar"
dev_addr: "127.0.0.1:8000"
docs_dir: docs
site_author: "Mohit Kumar" 
site_description: "My Notes for 101 Days of AWS"
repo_url: "https://github.com/mohitkr05/101daysofaws"

theme: 
 name: "material"

# extra_css:
#   - stylesheets/extra.css

nav:
  - Home: "index.md"
  - Join Discord:  "https://discord.gg/tnZnWqnu9F"

markdown_extensions:
  - extra
  - toc
  - codehilite
  - tables
  - meta 
  - toc
  - footnotes
  - admonition
  - attr_list
  - pymdownx.tasklist
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg